In [87]:
import pandas as pd

months = [10,11,12]
taxi_dtypes = {
                'VendorID': pd.Int64Dtype(),
                'passenger_count': pd.Int64Dtype(),
                'trip_distance': float,
                'RatecodeID':pd.Int64Dtype(),
                'store_and_fwd_flag':str,
                'PULocationID':pd.Int64Dtype(),
                'DOLocationID':pd.Int64Dtype(),
                'payment_type': pd.Int64Dtype(),
                'fare_amount': float,
                'extra':float,
                'mta_tax':float,
                'tip_amount':float,
                'tolls_amount':float,
                'improvement_surcharge':float,
                'total_amount':float,
                'congestion_surcharge':float
                }
parse_dates = ['lpep_pickup_datetime','lpep_dropoff_datetime']
df_concat = pd.DataFrame()
for month in months:
    # pd.read_csv('green_tripdata_2020-{month}.csv.gz
    url = f'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2020-{month}.csv.gz'
    # df = pd.DataFrame()
    df = pd.read_csv(url,dtype=taxi_dtypes,parse_dates=parse_dates);
    print("Each Dataframe length before concat",len(df))
    print(df)
    df_concat = pd.concat([df_concat,df])
    print("Each df_concat length after concat",len(df_concat))

Each Dataframe length before concat 95120
       VendorID lpep_pickup_datetime lpep_dropoff_datetime store_and_fwd_flag  \
0             2  2020-10-01 00:31:19   2020-10-01 00:34:55                  N
1             2  2020-10-01 00:42:12   2020-10-01 00:43:51                  N
2             2  2020-10-01 00:53:09   2020-10-01 00:55:39                  N
3             1  2020-10-01 00:12:29   2020-10-01 00:20:08                  N
4             1  2020-10-01 00:32:38   2020-10-01 00:43:02                  N
...         ...                  ...                   ...                ...
95115      <NA>  2020-10-19 14:28:00   2020-10-19 14:46:00                NaN
95116      <NA>  2020-10-19 14:57:00   2020-10-19 15:21:00                NaN
95117      <NA>  2020-10-19 14:01:00   2020-10-19 14:13:00                NaN
95118      <NA>  2020-10-19 14:53:00   2020-10-19 14:59:00                NaN
95119      <NA>  2020-10-19 14:22:00   2020-10-19 15:02:00                NaN

       RatecodeID  PULocationID  DOLocationID  passenger_count  trip_distance  \
0               1             7             7                1           0.79
1               1           179             7                1           0.50
2               1           179           223                1           0.60
3               1           134           216                2           4.40
4               1            82             7                1           2.90
...           ...           ...           ...              ...            ...
95115        <NA>           130            70             <NA>           6.29
95116        <NA>            13            42             <NA>          11.42
95117        <NA>            61            62             <NA>           1.33
95118        <NA>           205            10             <NA>           1.40
95119        <NA>           106            14             <NA>           4.60

       fare_amount  extra  mta_tax  tip_amount  tolls_amount  ehail_fee  \
0             5.00    0.5      0.5        1.58           0.0        NaN
1             4.00    0.5      0.5        0.00           0.0        NaN
2             4.00    0.5      0.5        1.06           0.0        NaN
3            13.50    0.5      0.5        0.00           0.0        NaN
4            10.50    0.5      0.5        0.00           0.0        NaN
...            ...    ...      ...         ...           ...        ...
95115        27.70    0.0      0.0        2.75           0.0        NaN
95116        41.11    0.0      0.0        2.75           0.0        NaN
95117        16.73    0.0      0.0        2.75           0.0        NaN
95118        18.58    0.0      0.0        2.75           0.0        NaN
95119        25.79    0.0      0.0        2.75           0.0        NaN

       improvement_surcharge  total_amount  payment_type  trip_type  \
0                        0.3          7.88             1        1.0
1                        0.3          5.30             2        1.0
2                        0.3          6.36             1        1.0
3                        0.3         14.80             2        1.0
4                        0.3         11.80             2        1.0
...                      ...           ...           ...        ...
95115                    0.3         30.75          <NA>        NaN
95116                    0.3         44.16          <NA>        NaN
95117                    0.3         19.78          <NA>        NaN
95118                    0.3         21.63          <NA>        NaN
95119                    0.3         28.84          <NA>        NaN

       congestion_surcharge
0                       0.0
1                       0.0
2                       0.0
3                       0.0
4                       0.0
...                     ...
95115                   NaN
95116                   NaN
95117                   NaN
95118                   NaN
95119                   NaN

[95120 rows x 20 columns]
Each df_concat length after concat 95120
Each Dataframe length before concat 88605
       VendorID lpep_pickup_datetime lpep_dropoff_datetime store_and_fwd_flag  \
0             2  2020-11-01 00:08:23   2020-11-01 00:32:03                  N
1             2  2020-11-01 00:23:32   2020-11-01 00:32:10                  N
2             2  2020-11-01 00:43:14   2020-11-01 00:54:54                  N
3             2  2020-11-01 00:33:13   2020-11-01 00:47:23                  N
4             2  2020-11-01 00:49:28   2020-11-01 00:53:54                  N
...         ...                  ...                   ...                ...
88600      <NA>  2020-11-30 23:06:00   2020-11-30 23:18:00                NaN
88601      <NA>  2020-11-30 23:24:00   2020-11-30 23:43:00                NaN
88602      <NA>  2020-11-30 23:59:00   2020-12-01 00:32:00                NaN
88603      <NA>  2020-11-30 23:53:00   2020-12-01 00:10:00                NaN
88604      <NA>  2020-11-30 23:04:00   2020-11-30 23:10:00                NaN

       RatecodeID  PULocationID  DOLocationID  passenger_count  trip_distance  \
0               5            97            75                1          10.49
1               1            41           127                1           4.52
2               1            42           213                1           6.51
3               1            78           212                1           1.95
4               1           134           134                2           1.02
...           ...           ...           ...              ...            ...
88600        <NA>           168           235             <NA>           3.99
88601        <NA>           212            41             <NA>           6.41
88602        <NA>            37           117             <NA>          11.90
88603        <NA>           247           259             <NA>           8.08
88604        <NA>           146           226             <NA>           1.42

       fare_amount  extra  mta_tax  tip_amount  tolls_amount  ehail_fee  \
0            28.03    0.0      0.0        3.40          0.00        NaN
1            14.00    0.5      0.5        1.00          0.00        NaN
2            19.50    0.5      0.5        0.00          0.00        NaN
3            11.00    0.5      0.5        0.00          0.00        NaN
4             5.50    0.5      0.5        0.00          0.00        NaN
...            ...    ...      ...         ...           ...        ...
88600        18.52    0.0      0.0        2.75          0.00        NaN
88601        26.83    0.0      0.0        2.75          6.12        NaN
88602        46.56    0.0      0.0        2.75          2.29        NaN
88603        31.31    0.0      0.0        2.75          0.00        NaN
88604         8.41    0.0      0.0        4.78          0.00        NaN

       improvement_surcharge  total_amount  payment_type  trip_type  \
0                        0.3         34.48             1        1.0
1                        0.3         16.30             1        1.0
2                        0.3         20.80             1        1.0
3                        0.3         12.30             2        1.0
4                        0.3          6.80             2        1.0
...                      ...           ...           ...        ...
88600                    0.3         21.57          <NA>        NaN
88601                    0.3         36.00          <NA>        NaN
88602                    0.3         51.90          <NA>        NaN
88603                    0.3         34.36          <NA>        NaN
88604                    0.3         13.49          <NA>        NaN

       congestion_surcharge
0                      2.75
1                      0.00
2                      0.00
3                      0.00
4                      0.00
...                     ...
88600                   NaN
88601                   NaN
88602                   NaN
88603                   NaN
88604                   NaN

[88605 rows x 20 columns]
Each df_concat length after concat 183725
Each Dataframe length before concat 83130
       VendorID lpep_pickup_datetime lpep_dropoff_datetime store_and_fwd_flag  \
0             2  2020-12-01 00:29:37   2020-12-01 00:32:51                  N
1             2  2020-12-01 00:41:46   2020-12-01 00:46:31                  N
2             2  2020-12-01 00:05:46   2020-12-01 00:10:48                  N
3             2  2020-11-30 23:59:17   2020-12-01 00:16:06                  N
4             2  2020-12-01 00:57:03   2020-12-01 01:00:29                  N
...         ...                  ...                   ...                ...
83125      <NA>  2020-12-31 23:02:00   2020-12-31 23:16:00                NaN
83126      <NA>  2020-12-31 23:39:00   2020-12-31 23:54:00                NaN
83127      <NA>  2020-12-31 23:09:00   2020-12-31 23:33:00                NaN
83128      <NA>  2020-12-31 23:01:00   2020-12-31 23:12:00                NaN
83129      <NA>  2020-12-31 23:12:00   2020-12-31 23:37:00                NaN

       RatecodeID  PULocationID  DOLocationID  passenger_count  trip_distance  \
0               1            75            75                1           0.59
1               1            75            74                1           1.24
2               1           244           243                2           1.19
3               1            75            68                1           5.08
4               1            74           263                1           1.24
...           ...           ...           ...              ...            ...
83125        <NA>           174           168             <NA>           7.04
83126        <NA>           256           225             <NA>           2.79
83127        <NA>           146            10             <NA>          12.41
83128        <NA>           196            28             <NA>           4.46
83129        <NA>           215            35             <NA>          10.34

       fare_amount  extra  mta_tax  tip_amount  tolls_amount  ehail_fee  \
0             4.50    0.5      0.5        1.16           0.0        NaN
1             6.00    0.5      0.5        1.46           0.0        NaN
2             6.00    0.5      0.5        1.46           0.0        NaN
3            17.00    0.5      0.5        2.00           0.0        NaN
4             5.50    0.5      0.5        0.00           0.0        NaN
...            ...    ...      ...         ...           ...        ...
83125        20.33    0.0      0.0        0.00           0.0        NaN
83126        13.17    0.0      0.0        0.00           0.0        NaN
83127        45.12    0.0      0.0        2.75           0.0        NaN
83128        13.96    0.0      0.0        3.13           0.0        NaN
83129        39.95    0.0      0.0        2.75           0.0        NaN

       improvement_surcharge  total_amount  payment_type  trip_type  \
0                        0.3          6.96             1        1.0
1                        0.3          8.76             1        1.0
2                        0.3          8.76             1        1.0
3                        0.3         23.05             1        1.0
4                        0.3          9.55             2        1.0
...                      ...           ...           ...        ...
83125                    0.3         20.63          <NA>        NaN
83126                    0.3         13.47          <NA>        NaN
83127                    0.3         48.17          <NA>        NaN
83128                    0.3         17.39          <NA>        NaN
83129                    0.3         43.00          <NA>        NaN

       congestion_surcharge
0                      0.00
1                      0.00
2                      0.00
3                      2.75
4                      2.75
...                     ...
83125                   NaN
83126                   NaN
83127                   NaN
83128                   NaN
83129                   NaN

[83130 rows x 20 columns]
Each df_concat length after concat 266855

In [88]:
# df_concat.rename(columns={'VendorID': 'vendor_id',}, inplace=True)
# df_concat.info()
df_concat['NewDate'] = (df_concat['lpep_pickup_datetime']).dt.date

In [96]:
df_concat['passenger_count'].isin([0]).sum() 
df_concat = df_concat[(df_concat['passenger_count'] > 0) & (df_concat['trip_distance'] > 0)]
print("after",df_concat['passenger_count'].isin([0]).sum())
if df_concat['passenger_count'].isin([0]).sum() > 0: 
    print('true')
else:
    print('false')

after 0
false

In [97]:
df_concat.describe()

,VendorID,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
count,139370.0,139370.0,139370.0,139370.0,139370.0,139370.000000,139370.000000,139370.000000,139370.000000,139370.000000,139370.000000,0.0,139370.000000,139370.000000,139370.0,139370.000000,139370.000000
mean,1.842419,1.108646,95.758112,131.108739,1.303143,3.825526,13.894763,0.381842,0.484584,1.410935,0.272862,NaN,0.296655,17.244192,1.438251,1.022551,0.599213
std,0.364349,0.645411,62.858319,77.623953,1.008511,118.071060,13.379482,0.665281,0.092893,2.099610,1.366296,NaN,0.037732,15.077427,0.51791,0.148469,1.135163
min,1.0,1.0,1.0,1.0,1.0,0.010000,-52.000000,-1.000000,-0.500000,0.000000,0.000000,NaN,-0.300000,-52.800000,1.0,1.000000,0.000000
25%,2.0,1.0,43.0,68.0,1.0,1.140000,6.500000,0.000000,0.500000,0.000000,0.000000,NaN,0.300000,8.800000,1.0,1.000000,0.000000
50%,2.0,1.0,75.0,129.0,1.0,1.910000,10.000000,0.000000,0.500000,0.200000,0.000000,NaN,0.300000,12.660000,1.0,1.000000,0.000000
75%,2.0,1.0,127.0,197.0,1.0,3.670000,15.500000,0.500000,0.500000,2.510000,0.000000,NaN,0.300000,19.850000,2.0,1.000000,0.000000
max,2.0,5.0,265.0,265.0,9.0,35757.460000,383.500000,4.500000,0.500000,111.600000,27.500000,NaN,0.300000,393.640000,5.0,2.000000,2.750000